version: '3.8'

services:
  web:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./www:/var/www/html
    depends_on:
      - php

  php:
    image: php:8.1-fpm
    volumes:
      - ./www:/var/www/html

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "5050:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306

  services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 1111  # รหัสผ่านสำหรับ root
      MYSQL_DATABASE: mydatabase  # ชื่อฐานข้อมูลเริ่มต้น
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
